### ISSUE TITLE
Production environment problem

### ISSUE THREAD

**Issue by osoner** [jockster/paypal-recurring#1]
First of all thanks a lot for this great module. I've found below issues about production usage. I'm not sending a pull req in case you might wanna change the implementation.
- The environment property needs to be given as the second parameter to the constructor in order work
  
  ```
  var Paypal = require('paypal-recurring'),
      paypal = new Paypal({
        username:  "info@example.com",
        password:  "****",
        signature: "****"
      }, "production");
  ```
- [Line 33](https://github.com/jaybryant/paypal-recurring/blob/master/lib/Paypal.coffee#L33) should be changed from `cgi?bin` to `cgi-bin`

**Comment by labe-me** [comment]
Hello and thank you for the lib.
Is it possible to update the npm version?
