### ISSUE TITLE
username, password, signature - not supported anymore?

### ISSUE THREAD

**Issue by lefnire** [jockster/paypal-recurring#3]
Can't seem to find the variables [required here](https://github.com/jaybryant/paypal-recurring#constructor) - specifically `signature`. At developer.paypal.com, the credentials I see are `Client ID` & `Secret` ([screenshot](https://www.evernote.com/shard/s17/sh/02fb0896-06ff-4b58-8197-6fd3e2ada7a4/4e4a5ebb4979d5d9658da3d1ade7344a)). Is `signature` buried somewhere else, or has paypal changed?

**Comment by lefnire** [comment]
[Found it](https://www.paypal.com/us/cgi-bin/webscr?cmd=_profile-api-signature). paypal.com > My Account > Profile > Request API credentials > (Option 2) View API Signature. This is the "Classic API", which it seems they're trying somewhat to hide in lieu of their new REST API

**Comment by fiatjaf** [comment]
Thank you very much, @lefnire.
